# Generated by Django 4.0.1 on 2022-01-31 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, choices=[('MOBILE', 'Mobile'), ('LAPTOP', 'Laptop')], max_length=55, null=True)),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
        migrations.CreateModel(
            name='MobileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('processor', models.TextField()),
                ('ram', models.CharField(max_length=100)),
                ('screen_size', models.TextField()),
                ('color', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronicsapp.productdetail')),
            ],
            options={
                'db_table': 'mobile_details',
            },
        ),
        migrations.CreateModel(
            name='LaptopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('processor', models.TextField()),
                ('ram', models.CharField(max_length=100)),
                ('hd_capacity', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronicsapp.productdetail')),
            ],
            options={
                'db_table': 'laptop_details',
            },
        ),
    ]
