# Generated by Django 4.0.1 on 2022-02-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopdetail',
            name='hd_capacity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobiledetail',
            name='screen_size',
            field=models.CharField(max_length=100),
        ),
    ]
