# Generated by Django 4.0.1 on 2022-02-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronicsapp', '0002_alter_laptopdetail_hd_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptopdetail',
            options={'default_related_name': 'laptops'},
        ),
        migrations.AlterModelOptions(
            name='mobiledetail',
            options={'default_related_name': 'mobiles'},
        ),
    ]
