"""
Django settings for electronicproducts project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l4rf)e=mqe_5%6xd7%cc+lzo-#8!ks9ih!(*-m9)=ul4!&pm1i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'ajax_select',

    # user defined packages
    'electronicproducts.electronicsapp',
    'electronicproducts.userapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'electronicproducts.urls'

#AUTH_USER_MODEL = 'userapp.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'electronicproducts/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'electronicproducts.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

MYSQL_DB_HOST = os.environ.get('MYSQL_DB_HOST', 'localhost')
MYSQL_DB_PORT = os.environ.get('MYSQL_DB_PORT', '3306')
MYSQL_DB_USER = os.environ.get('MYSQL_DB_USER', 'root')
MYSQL_DB_PWD = os.environ.get('MYSQL_DB_PWD', 'root')
MYSQL_DB_MAIN_DBNAME = os.environ.get('MYSQL_DB_MAIN_DBNAME', 'electronics')
MYSQL_DB_TEST_DBNAME = os.environ.get('MYSQL_DB_TEST_DBNAME', 'test_electronics')

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.mysql',
       'NAME': MYSQL_DB_MAIN_DBNAME,
       'USER': MYSQL_DB_USER,
       'PASSWORD': MYSQL_DB_PWD,
       'HOST': MYSQL_DB_HOST,
       'PORT': MYSQL_DB_PORT,
       'TEST': {
            'NAME': MYSQL_DB_TEST_DBNAME,
            'USER': MYSQL_DB_USER,
            'PASSWORD': MYSQL_DB_PWD
       }
    },
}



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join('electronicproducts/', 'static'),
]